services:
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres@15
    volumes:
      - postgres:/data/postgres@15
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  amigoscode-api:
    container_name: amigoscode-api
    image: ajosslyn/amigoscode-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      SPRING_DATASOURCE_USERNAME: amigoscode
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8088:8080"
    networks:
        - postgres
    depends_on:
        - db
    restart: unless-stopped

#  app:
#    image: ajosslyn/amigoscode-api
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
#      SPRING_DATASOURCE_USERNAME: amigoscode
#      SPRING_DATASOURCE_PASSWORD: password
#    ports:
#      - "8081:8080"
#    networks:
#      - postgres
#    depends_on:
#      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: